### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by dzsabo**
No issues found on dev after updating many modules.

### CODE REVIEW

**Comment by czigor** [comment]
I've already updated Media to 2.20, that's a security release. It should not be downgraded back.

**Comment by dzsabo** [comment]
I don't quite understand @czigor. Currently Media 7.x-2.19  is the latest stable release and is recommended by the project’s maintainer: (https://www.drupal.org/project/media. Also https://github.com/czigor/zenekar/compare/firsttry...dev does not display any changes at sites/all/modules/contrib/media/.

**Comment by czigor** [comment]
You're right, media is fine. But file_entity should be 2.20 instead of 3.0-beta6. At least I believe media 2 works only with the file entity 2 branch.

**Comment by dzsabo** [comment]
Indeed, it should be 2.20. 
(Next time I will pull request from my branch instead of dev to be able to add commits easier.)

**Pull request merged**
